# Generated by Django 4.0.8 on 2022-10-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_accounts_uid_usercart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x7f48e71e2710>', max_length=200),
        ),
    ]
