# Generated by Django 4.0.8 on 2022-11-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_coupon_alter_accounts_uid_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000002192F1C3010>', max_length=200),
        ),
    ]
