# Generated by Django 4.0.8 on 2022-11-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_usercart_cancel_usercart_price_with_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001BDCCEC3010>', max_length=200),
        ),
    ]
